ForoToronja/ForoToronja/urls.py
from django.contrib import admin
from django.urls import path, include
from publicaciones.views import inicio, acerca_de
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),  
    path('acerca-de/', acerca_de, name='acerca_de'),  
    path('cuentas/', include('cuentas.urls')),  
    path('mensajeria/', include('mensajeria.urls')),  
    path('paginas/', include('paginas.urls')),  
    path('publicaciones/', include('publicaciones.urls')),
    path('cuentas/', include('cuentas.urls', namespace='cuentas')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForoToronja/cuentas/urls.py
from django.urls import path , include
from . import views

app_name = 'cuentas'

urlpatterns = [
    path('registro/', views.RegistroUsuarioView.as_view(), name='registro'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('perfil/<int:pk>/', views.PerfilView.as_view(), name='perfil'),
    path('perfil/editar/<int:pk>/', views.ActualizarPerfilView.as_view(), name='editar_perfil'),
    
]

ForoToronja/cuentas/models.py
from django.contrib.auth.models import User
from django.db import models

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.user.username

ForoToronja/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Perfil

class FormularioRegistroUsuario(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
class FormularioActualizarPerfil(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['avatar', 'bio', 'fecha_nacimiento']

ForoToronja/cuentas/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from .models import Perfil
from .forms import FormularioRegistroUsuario, FormularioActualizarPerfil
from django.contrib.auth import login



class RegistroUsuarioView(CreateView):
    form_class = FormularioRegistroUsuario
    template_name = 'cuentas/registro.html'
    success_url = reverse_lazy('inicio')  # Redirige después del registro exitoso

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)  # Inicia sesión automáticamente después del registro
        return super().form_valid(form)  # Retorna la respuesta adecuada
        

class LoginView(LoginView):
    template_name = 'cuentas/login.html'

class LogoutView(LogoutView):
    next_page = 'inicio'

class PerfilView(DetailView):
    model = Perfil
    template_name = 'cuentas/perfil.html'
    context_object_name = 'perfil'

#class ActualizarPerfilView(UpdateView):
#    model = Perfil
#    form_class = FormularioActualizarPerfil
#    template_name = 'cuentas/actualizar_perfil.html'
#    success_url = reverse_lazy('perfil')
#    def get_success_url(self):
#        return reverse_lazy('perfil', kwargs={'pk': self.object.pk})
    
class ActualizarPerfilView(UpdateView):
    model = Perfil
    form_class = FormularioActualizarPerfil
    template_name = 'cuentas/actualizar_perfil.html'

    def get_success_url(self):
        return reverse_lazy('cuentas:perfil', kwargs={'pk': self.object.pk})

ForoToronja/cuentas/templates/cuentas/actualizar_perfil.html
{% extends 'base.html' %}

{% block titulo %}Actualizar perfil - ForoToronja{% endblock %}

{% block contenido %}
    <h1>Actualizar perfil</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock %}

ForoToronja/cuentas/templates/cuentas/login.html
{% extends 'base.html' %}

{% block titulo %}Iniciar sesión - ForoToronja{% endblock %}

{% block contenido %}
    <h1>Iniciar sesión</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar sesión</button>
    </form>
{% endblock %}

ForoToronja/cuentas/templates/cuentas/perfil.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">


{% block titulo %}Perfil - ForoToronja{% endblock %}

{% block contenido %}
<h1>{{ user.username }}</h1>
    {% if perfil.avatar %}
    <img src="{{ perfil.avatar.url }}" alt="Avatar de {{ perfil.user.username }}" style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover;">
    {% else %}
    <p>No hay avatar disponible.</p>
    {% endif %}
<div class='contenedor'>
    <p>Biografia: {{ perfil.bio }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Fecha de nacimiento: {{ user.perfil.fecha_nacimiento }}</p>
</div>
    <a href="{% url 'cuentas:editar_perfil' user.perfil.pk %}">Editar perfil</a>
{% endblock %}

ForoToronja/cuentas/templates/cuentas/registro.html
{% extends 'base.html' %}

{% block contenido %}
<h2>Registro</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrarse</button>
</form>
<p>¿Ya tienes una cuenta? <a href="{% url 'cuentas:login' %}">Inicia sesión aquí</a></p>
{% endblock %}