ForoToronja/ForoToronja/urls.py
from django.contrib import admin
from django.urls import path, include
from publicaciones.views import inicio, acerca_de
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),  
    path('acerca-de/', acerca_de, name='acerca_de'),  
    path('cuentas/', include('cuentas.urls')),  
    path('mensajeria/', include('mensajeria.urls')),  
    path('paginas/', include('paginas.urls')),  
    path('publicaciones/', include('publicaciones.urls')),
    path('cuentas/', include('cuentas.urls', namespace='cuentas')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForoToronja/cuentas/urls.py
from django.urls import path , include
from . import views

app_name = 'cuentas'

urlpatterns = [
    path('registro/', views.RegistroUsuarioView.as_view(), name='registro'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('perfil/<int:pk>/', views.PerfilView.as_view(), name='perfil'),
    path('perfil/editar/<int:pk>/', views.ActualizarPerfilView.as_view(), name='editar_perfil'),
    
]

ForoToronja/paginas/urls.py
from django.urls import path
from . import views

app_name = 'paginas'  
urlpatterns = [
    path('lista/', views.ListaPaginasView.as_view(), name='lista'),
    path('crear/', views.CrearPaginaView.as_view(), name='crear'),  
    path('detalle/<int:pk>/', views.DetallePaginaView.as_view(), name='detalle'),  
    path('editar/<int:pk>/', views.EditarPaginaView.as_view(), name='editar'),  
    path('eliminar/<int:pk>/', views.EliminarPaginaView.as_view(), name='eliminar'), 
]

ForoToronja/templates/acerca_de.html
{% extends 'base.html' %}

{% block titulo %}Acerca de - ForoToronja{% endblock %}

{% block contenido %}
    <h1>Acerca de</h1>
    <h2>Jonathan Silvera</h2>
    <div class='contenedor'>
    <p>¡Hola! Mi nombre es Jonathan Silvera, tengo 28 años y soy un apasionado del desarrollo y la tecnología. Este proyecto, ForoToronja, es parte de mi curso de Python en CoderHouse, donde estoy aprendiendo a crear aplicaciones web dinámicas y funcionales utilizando Django.
    
    Desde que comencé mi viaje en el mundo de la programación, he descubierto un gran interés por resolver problemas, crear soluciones innovadoras y mejorar mis habilidades día a día. Este proyecto es un reflejo de ese esfuerzo y dedicación, donde he aplicado todo lo aprendido para construir una plataforma interactiva y útil.
    
    Mi objetivo es seguir creciendo como desarrollador, explorando nuevas tecnologías y contribuyendo a proyectos que tengan un impacto positivo en la comunidad. ¡Gracias por visitar ForoToronja y ser parte de este viaje!.</p>
</div>
    {% endblock %}

ForoToronja/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block titulo %}ForoToronja{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="menu" id="nav">
        <a href="{% url 'inicio' %}"> Inicio   </a>
        <a href="{% url 'acerca_de' %}"> Acerca de   </a>
        <a href="{% url 'paginas:lista' %}">Posteos   </a>
        {% if user.is_authenticated %}
        <a href="{% url 'cuentas:perfil' user.pk %}"> Perfil</a>
        <form action="{% url 'cuentas:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit"> Cerrar sesión   </button>
        </form>
        {% else %}
        <form action="{% url 'cuentas:login' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn"> Iniciar sesión   </button>
        </form>
        <form action="{% url 'cuentas:registro' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn"> Registrarse    </button>
        </form>
        {% endif %}
    </nav>
    {% block contenido %}{% endblock %}
</body>
</html>

ForoToronja/templates/inicio.html
{% extends 'base.html' %}

{% block titulo %}Inicio - ForoToronja{% endblock %}

{% block contenido %}
    <section class='wrapper'>
        <div class='hero'>
        </div>
        <div class='content'>
          <h1 class='h1--scalingSize' data-text='An awesome title'>Foro Toronja</h1>
          <input type='checkbox' id='switch'>
          <label for='switch'><span><span class='icon'>→</span> switch background</span></label>
        </div>
    </section>
{% endblock %}