ForoToronja/ForoToronja/urls.py
from django.contrib import admin
from django.urls import path, include
from publicaciones.views import inicio, acerca_de
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),  
    path('acerca-de/', acerca_de, name='acerca_de'),  
    path('cuentas/', include('cuentas.urls')),  
    path('mensajeria/', include('mensajeria.urls')),  
    path('paginas/', include('paginas.urls')),  
    path('publicaciones/', include('publicaciones.urls')),
    path('cuentas/', include('cuentas.urls', namespace='cuentas')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForoToronja/cuentas/urls.py
from django.urls import path , include
from . import views

app_name = 'cuentas'

urlpatterns = [
    path('registro/', views.RegistroUsuarioView.as_view(), name='registro'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('perfil/<int:pk>/', views.PerfilView.as_view(), name='perfil'),
    path('perfil/editar/<int:pk>/', views.ActualizarPerfilView.as_view(), name='editar_perfil'),
    
]

ForoToronja/paginas/urls.py
from django.urls import path
from . import views

app_name = 'paginas'  
urlpatterns = [
    path('lista/', views.ListaPaginasView.as_view(), name='lista'),
    path('crear/', views.CrearPaginaView.as_view(), name='crear'),  
    path('detalle/<int:pk>/', views.DetallePaginaView.as_view(), name='detalle'),  
    path('editar/<int:pk>/', views.EditarPaginaView.as_view(), name='editar'),  
    path('eliminar/<int:pk>/', views.EliminarPaginaView.as_view(), name='eliminar'), 
]

ForoToronja/paginas/models.py
from django.db import models
from django.utils import timezone

class Pagina(models.Model):
    titulo = models.CharField(max_length=200)
    subtitulo = models.CharField(max_length=200)
    contenido = models.TextField()
    imagen = models.ImageField(upload_to='paginas/')
    fecha = models.DateTimeField(default=timezone.now) 

    def __str__(self):
        return self.titulo
    
    

ForoToronja/paginas/forms.py
from django import forms
from .models import Pagina  

class PaginaForm(forms.ModelForm):
    class Meta:
        model = Pagina
        fields = ['titulo', 'subtitulo', 'contenido', 'imagen']  

ForoToronja/paginas/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Pagina
from .forms import PaginaForm
from django.urls import reverse_lazy


class ListaPaginasView(ListView):
    model = Pagina
    template_name = 'paginas/lista.html'
    context_object_name = 'paginas'

class DetallePaginaView(DetailView):
    model = Pagina
    template_name = 'paginas/detalle.html'

class CrearPaginaView(CreateView):
    model = Pagina
    form_class = PaginaForm
    template_name = 'paginas/crear.html'
    success_url = reverse_lazy('paginas:lista')
    def form_valid(self, form):
        return super().form_valid(form)  

class EditarPaginaView(UpdateView):
    model = Pagina
    fields = ['titulo', 'subtitulo', 'contenido', 'imagen']
    template_name = 'paginas/editar.html'
    success_url = reverse_lazy('paginas:editar')

class EliminarPaginaView(DeleteView):
    model = Pagina
    success_url = '/paginas/lista/'
    template_name = 'paginas/eliminar.html'

ForoToronja/paginas/templates/paginas/crear.html
{% extends 'base.html' %}

{% block contenido %}
<h2>Crear Nuevo Posteo</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Crear</button>
</form>
<a href="{% url 'paginas:lista' %}">Cancelar</a>
{% endblock %}

ForoToronja/paginas/templates/paginas/detalle.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block titulo %}{{ pagina.titulo }} - ForoToronja{% endblock %}

{% block contenido %}
    <h1>Titulo: {{ pagina.titulo }}</h1>
    <h2>Subtitulo: {{ pagina.subtitulo }}</h2>
    <img src="{{ pagina.imagen.url }}" alt="{{ pagina.titulo }}" class="pagina-img" style="max-width: 50%;
    height: auto;">
    <p>Detalles: {{ pagina.contenido }}</p>
    <p>Fecha: {{ pagina.fecha }}</p>
    {% if user.is_authenticated %}
        <a href="{% url 'paginas:editar' pagina.id %}">Editar</a>
        <a href="{% url 'paginas:eliminar' pagina.id %}">Eliminar</a>
    {% endif %}
{% endblock %}

ForoToronja/paginas/templates/paginas/editar.html
{% extends 'base.html' %}

{% block contenido %}
<h2>Editar Página</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
</form>
<a href="{% url 'paginas:lista' %}">Cancelar</a>
{% endblock %}

ForoToronja/paginas/templates/paginas/eliminar.html
{% extends 'base.html' %}

{% block contenido %}
<h2>Eliminar Página</h2>
<p>¿Estás seguro de que deseas eliminar "{{ object }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
</form>
<a href="{% url 'paginas:lista' %}">Cancelar</a>
{% endblock %}

ForoToronja/paginas/templates/paginas/lista.html
{% extends 'base.html' %}

{% block title %}Posts - ForoToronja{% endblock %}

{% block contenido %}
<h1 class='titulo-posteos'>Lista de Posteos</h1>
<div class='container lista-posteos'>
{% if paginas %}
    <ul>
    {% for pagina in paginas %}
        <li>
            <a href="{% url 'paginas:detalle' pagina.id %}">{{ pagina.titulo }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay páginas aún.</p>
{% endif %}
</div>
<a href="{% url 'paginas:crear' %}" class='crear-posteo'>Crear nuevo posteo</a>
{% endblock %}